apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-tester.fullname" . }}-properties
  labels:
    {{- include "api-tester.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}